sudo: required

services:
  - docker

env:
  matrix:
  - OS="gr-iio.docker.ubuntu18.04"
  - OS="gr-iio.docker.ubuntu16.04"
  - OS="gr-iio.docker.centos7"
  - OS="gr-iio.docker.debian9"
  - OS="pybombs.docker.ubuntu17.04"
  - OS="pybombs.docker.ubuntu16.04"
  - OS="pybombs.docker.centos7"

before_install:
  - docker build . -t $OS  -f $OS
  - docker run -d $OS
